### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by broberson** [Health-Tracker-CET/health-tracker-backend#3]
When you commit changes to a git repository, the old code is still in the history of the repo. Deleting private keys doesn't remove them from the history, and your keys are still available here: https://github.com/Health-Tracker-CET/health-tracker-backend/commit/9c1de1dfc07e0b418412a4ae5e326cfd5f439b7f

You should generate new keys, keep them in a file that's .gitignored, and never check them in. Your existing keys are compromised and should be disabled immediately.

**Comment by harisumaid** [comment]
Thanks @broberson for pointing that out.
Created new configs and deleted those old one's.

**Comment by harisumaid** [comment]
Ok it seems i just created a new key old one was not disabled. Thanks again for pointing that out
